index:
  path: /
  defaults: { _controller: 'Controller\ApplicationController::indexAction' }

contact:
  path: /contact-us
  defaults: { _controller: 'Controller\ApplicationController::contactAction' }

user-panel: 
  path: /user
  defaults: { _controller: 'Controller\ApplicationController::userPanelAction' }


get-todo-json:
  path: /todo-json
  defaults: { _controller: 'Controller\JsonController::getTodoJsonAction' }

about:
  path: /about-us
  defaults: { _controller: 'Controller\ApplicationController::aboutAction' }
